# Generated by Django 5.1.6 on 2025-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
