# Generated by Django 5.1.6 on 2025-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_identity_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
