# Generated by Django 5.1.6 on 2025-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
