# Generated by Django 5.1.6 on 2025-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bank_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_details',
            field=models.BooleanField(default=False),
        ),
    ]
